version: "3.9"

services:
  portfolio:
    build: .
    ports:
      - "3000"
    networks:
      portfolio:
        ipv4_address: 172.5.0.253

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      portfolio:
        ipv4_address: 172.5.0.254

networks:
  portfolio:
    ipam:
      config:
        - subnet: 172.5.0.0/24
